name: teknofest_helen_project_
description: A new Flutter project.


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  carousel_slider: ^4.1.1
  font_awesome_flutter: ^10.1.0
  audioplayers: ^0.20.1
  url_launcher: ^6.1.4
  get: ^4.6.5
  easy_localization: ^3.0.0
  shared_preferences: ^2.0.15
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1 
flutter_native_splash:
  background_image: "assets/images/taksimmeydanı.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

  
  flutter_lints: ^1.0.0


flutter:

  
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/  
    - assets/translations/  

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
